# Military Power Clustering Project
-World military power
Source : globalfirepower.com on 1st may 2020

- https://data.world/vizzup/world-military-power/workspace/file?filename=World+military+power.xlsx

# Import Libraries

In [16]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats

%matplotlib inline
sns.set_style("whitegrid")
plt.style.use("fivethirtyeight")

pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)
pd.set_option('display.width', 1000)

# Ingest Data

In [17]:
df = pd.read_excel("World military power.xlsx",header=[0,1])
df.head()

       2020 ranking                               Airforce Strength                                                                                                                                                                                                                                                                                                                                                                                                                 Land Strength                                                                                                                                                                                                                                                                Navy Strength                                                                                                                                                                                                                                          \
  Military Strength Military Strength Power Index Aircraft Strength Aircraft Strength value Fighter/Interceptor Strength Fighter/Interceptor Strength value Attack Aircraft Strength Attack Aircraft Strength value Transport Aircraft Fleet Strength Transport Aircraft Fleet Strength value Trainer Aircraft Fleet Trainer Aircraft Fleet value Helicopter Fleet Strength Helicopter Fleet Strength value Attack Helicopter Fleet Strength Attack Helicopter Fleet Strength value Tank Strength Tank Strength value AFV/APC Strength AFV/APC Strength value Self-Propelled Artillery Strength Self-Propelled Artillery Strength value Towed Artillery Strength Towed Artillery Strength value Rocket Projector Strength Rocket Projector Strength value Navy Fleet Strengths Navy Fleet Strengths value Aircraft Carrier Fleet Strength Aircraft Carrier Fleet Strength value Submarine Fleet Strength Submarine Fleet Strength value Destroyer Fleet Strength Destroyer Fleet Strength value Frigate Fleet Strength
0       Afghanistan                        1.3444       Afghanistan                   260.0                  Afghanistan                                0.0              Afghanistan                           25.0                       Afghanistan                                    30.0            Afghanistan                          0.0               Afghanistan                           187.0                      Afghanistan                                    0.0   Afghanistan                 0.0      Afghanistan                 1062.0                       Afghanistan                                     0.0              Afghanistan                          176.0               Afghanistan                            50.0          Afghanistan                        0.0                     Afghanistan                                   0.0              Afghanistan                            0.0              Afghanistan                            0.0            Afghanistan
1           Albania                        2.3137           Albania                    19.0                      Albania                                0.0                  Albania                            0.0                           Albania                                     0.0                Albania                          0.0                   Albania                            19.0                          Albania                                    0.0       Albania                 0.0          Albania                  467.0                           Albania                                     0.0                  Albania                            0.0                   Albania                             0.0              Albania                       38.0                         Albania                                   0.0                  Albania                            0.0                  Albania                            0.0                Albania
2           Algeria                        0.4659           Algeria                   551.0                      Algeria                              103.0                  Algeria                           22.0                           Algeria                                    59.0                Algeria                         87.0                   Algeria                           257.0                          Algeria                                   45.0       Algeria               880.0          Algeria                 7361.0                           Algeria                                   320.0                  Algeria                          240.0                   Algeria                           316.0              Algeria                      201.0                         Algeria                                   0.0                  Algeria                            6.0                  Algeria                            0.0                Algeria
3            Angola                        0.8379            Angola                   295.0                       Angola                               72.0                   Angola                           18.0                            Angola                                    30.0                 Angola                         47.0                    Angola                           126.0                           Angola                                   15.0        Angola               379.0           Angola                  595.0                            Angola                                    28.0                   Angola                          357.0                    Angola                           115.0               Angola                       57.0                          Angola                                   0.0                   Angola                            0.0                   Angola                            0.0                 Angola
4         Argentina                        0.6521         Argentina                   227.0                    Argentina                               24.0                Argentina                            7.0                         Argentina                                     9.0              Argentina                         64.0                 Argentina                           100.0                        Argentina                                    0.0     Argentina               370.0        Argentina                  739.0                         Argentina                                    83.0                Argentina                          172.0                 Argentina                            26.0            Argentina                       49.0                       Argentina                                   0.0                Argentina                            2.0                Argentina                            4.0              Argentina

                                              Finances                                                                      Logistics                      Natural resources                                                                                                                    Manpower                                                                               Geography
  Frigate Fleet Strength value defense spending budget defense spending budget value External Debt External Debt value Airport Totals Airport Totals value    Oil Production Oil Production value Oil Consumption Oil Consumption value Proven Oil Reserves Proven Oil Reserves value Available Manpower Available Manpower value Total Population Total Population value Total Square Land Area Total Square Land Area value Total Coastline Coverage Total Coastline Coverage value Total Waterway Coverage Total Waterway Coverage value Total Border Coverage Total Border Coverage value
0                          0.0             Afghanistan               12,00,00,00,000   Afghanistan      2,84,00,00,000    Afghanistan                 43.0       Afghanistan                  0.0     Afghanistan                5500.0         Afghanistan                       0.0        Afghanistan              1,43,25,743      Afghanistan            3,49,40,837            Afghanistan                     6,52,230              Afghanistan                            0.0             Afghanistan                        1200.0           Afghanistan                      5987.0
1                          0.0                 Albania                  25,00,00,000       Albania      9,50,50,00,000        Albania                  4.0           Albania              16000.0         Albania               42500.0             Albania              16,83,00,000            Albania                15,19,438          Albania              30,57,220                Albania                      28748.0                  Albania                          362.0                 Albania                          41.0               Albania                       691.0
2                          5.0                 Algeria               13,00,00,00,000       Algeria      6,26,00,00,000        Algeria                157.0           Algeria            13,06,000         Algeria              3,25,000             Algeria           12,20,00,00,000            Algeria              2,07,41,263          Algeria            4,16,57,488                Algeria                    23,81,741                  Algeria                          998.0                 Algeria                           0.0               Algeria                      6734.0
3                          0.0                  Angola                7,00,00,00,000        Angola     42,08,00,00,000         Angola                176.0            Angola            16,66,000          Angola               82300.0              Angola            8,27,30,00,000             Angola                62,44,205           Angola            3,03,55,880                 Angola                    12,46,700                   Angola                         1600.0                  Angola                        1300.0                Angola                      5369.0
4                          0.0               Argentina                4,20,00,00,000     Argentina   2,14,90,00,00,000      Argentina               1138.0         Argentina             4,79,400       Argentina              6,85,000           Argentina            2,18,50,00,000          Argentina              2,01,79,430        Argentina            4,46,94,198              Argentina                    27,80,400                Argentina                         4989.0               Argentina                       11000.0             Argentina                     11968.0

# EDA

In [18]:
df.shape

(138, 60)

In [19]:
df.isna().sum().any()

True

In [ ]:
df.duplicated().sum()

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 60 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   (2020 ranking, Military Strength)                             138 non-null    object
 1   (2020 ranking, Military Strength Power Index)                 138 non-null    float64
 2   (Airforce Strength, Aircraft Strength)                        138 non-null    object
 3   (Airforce Strength, Aircraft Strength value)                  138 non-null    float64
 4   (Airforce Strength, Fighter/Interceptor Strength)             138 non-null    object
 5   (Airforce Strength, Fighter/Interceptor Strength value)       138 non-null    float64
 6   (Airforce Strength, Attack Aircraft Strength)                 138 non-null    object
 7   (Airforce Strength, Attack Aircraft Strength value)           138 non-null    float64
 8   (Airforce Strength, Transport Aircraft Fleet Strength)        138 non-null    object
 9   (Airforce Strength, Transport Aircraft Fleet Strength value)  138 non-null    float64
 10  (Airforce Strength, Trainer Aircraft Fleet)                   138 non-null    object
 11  (Airforce Strength, Trainer Aircraft Fleet value)             138 non-null    float64
 12  (Airforce Strength, Helicopter Fleet Strength)                138 non-null    object
 13  (Airforce Strength, Helicopter Fleet Strength value)          138 non-null    float64
 14  (Airforce Strength, Attack Helicopter Fleet Strength)         138 non-null    object
 15  (Airforce Strength, Attack Helicopter Fleet Strength value)   138 non-null    float64
 16  (Land Strength, Tank Strength)                                138 non-null    object
 17  (Land Strength, Tank Strength value)                          138 non-null    float64
 18  (Land Strength, AFV/APC Strength)                             138 non-null    object
 19  (Land Strength, AFV/APC Strength value)                       138 non-null    float64
 20  (Land Strength, Self-Propelled Artillery Strength)            138 non-null    object
 21  (Land Strength, Self-Propelled Artillery Strength value)      138 non-null    float64
 22  (Land Strength, Towed Artillery Strength)                     138 non-null    object
 23  (Land Strength, Towed Artillery Strength value)               138 non-null    float64
 24  (Land Strength, Rocket Projector Strength)                    138 non-null    object
 25  (Land Strength, Rocket Projector Strength value)              138 non-null    float64
 26  (Navy Strength, Navy Fleet Strengths)                         124 non-null    object
 27  (Navy Strength, Navy Fleet Strengths value)                   124 non-null    float64
 28  (Navy Strength, Aircraft Carrier Fleet Strength)              115 non-null    object
 29  (Navy Strength, Aircraft Carrier Fleet Strength value)        115 non-null    float64
 30  (Navy Strength, Submarine Fleet Strength)                     115 non-null    object
 31  (Navy Strength, Submarine Fleet Strength value)               115 non-null    float64
 32  (Navy Strength, Destroyer Fleet Strength)                     115 non-null    object
 33  (Navy Strength, Destroyer Fleet Strength value)               115 non-null    float64
 34  (Navy Strength, Frigate Fleet Strength)                       115 non-null    object
 35  (Navy Strength, Frigate Fleet Strength value)                 115 non-null    float64
 36  (Finances, defense spending budget)                           138 non-null    object
 37  (Finances, defense spending budget value)                     138 non-null    object
 38  (Finances, External Debt)                                     138 non-null    object
 39  (Finances, External Debt value)                               138 non-null    object
 40  (Logistics, Airport Totals)                                   138 non-null    object
 41  (Logistics, Airport Totals value)                             138 non-null    float64
 42  (Natural resources, Oil Production)                           138 non-null    object
 43  (Natural resources, Oil Production value)                     138 non-null    object
 44  (Natural resources, Oil Consumption)                          138 non-null    object
 45  (Natural resources, Oil Consumption value)                    138 non-null    object
 46  (Natural resources, Proven Oil Reserves)                      138 non-null    object
 47  (Natural resources, Proven Oil Reserves value)                138 non-null    object
 48  (Manpower, Available Manpower)                                138 non-null    object
 49  (Manpower, Available Manpower value)                          138 non-null    object
 50  (Manpower, Total Population)                                  138 non-null    object
 51  (Manpower, Total Population value)                            138 non-null    object
 52  (Geography, Total Square Land Area)                           138 non-null    object
 53  (Geography, Total Square Land Area value)                     138 non-null    object
 54  (Geography, Total Coastline Coverage)                         109 non-null    object
 55  (Geography, Total Coastline Coverage value)                   109 non-null    object
 56  (Geography, Total Waterway Coverage)                          138 non-null    object
 57  (Geography, Total Waterway Coverage value)                    138 non-null    object
 58  (Geography, Total Border Coverage)                            129 non-null    object
 59  (Geography, Total Border Coverage value)                      129 non-null    float64
dtypes: float64(20), object(40)
memory usage: 64.8+ KB

In [21]:
df.columns

MultiIndex([(     '2020 ranking',                       'Military Strength'),
            (     '2020 ranking',           'Military Strength Power Index'),
            ('Airforce Strength',                       'Aircraft Strength'),
            ('Airforce Strength',                 'Aircraft Strength value'),
            ('Airforce Strength',            'Fighter/Interceptor Strength'),
            ('Airforce Strength',      'Fighter/Interceptor Strength value'),
            ('Airforce Strength',                'Attack Aircraft Strength'),
            ('Airforce Strength',          'Attack Aircraft Strength value'),
            ('Airforce Strength',       'Transport Aircraft Fleet Strength'),
            ('Airforce Strength', 'Transport Aircraft Fleet Strength value'),
            ('Airforce Strength',                  'Trainer Aircraft Fleet'),
            ('Airforce Strength',            'Trainer Aircraft Fleet value'),
            ('Airforce Strength',               'Helicopter Fleet Strength'),
            ('Airforce Strength',         'Helicopter Fleet Strength value'),
            ('Airforce Strength',        'Attack Helicopter Fleet Strength'),
            ('Airforce Strength',  'Attack Helicopter Fleet Strength value'),
            (    'Land Strength',                           'Tank Strength'),
            (    'Land Strength',                     'Tank Strength value'),
            (    'Land Strength',                        'AFV/APC Strength'),
            (    'Land Strength',                  'AFV/APC Strength value'),
            (    'Land Strength',       'Self-Propelled Artillery Strength'),
            (    'Land Strength', 'Self-Propelled Artillery Strength value'),
            (    'Land Strength',                'Towed Artillery Strength'),
            (    'Land Strength',          'Towed Artillery Strength value'),
            (    'Land Strength',               'Rocket Projector Strength'),
            (    'Land Strength',         'Rocket Projector Strength value'),
            (    'Navy Strength',                    'Navy Fleet Strengths'),
            (    'Navy Strength',              'Navy Fleet Strengths value'),
            (    'Navy Strength',         'Aircraft Carrier Fleet Strength'),
            (    'Navy Strength',   'Aircraft Carrier Fleet Strength value'),
            (    'Navy Strength',                'Submarine Fleet Strength'),
            (    'Navy Strength',          'Submarine Fleet Strength value'),
            (    'Navy Strength',                'Destroyer Fleet Strength'),
            (    'Navy Strength',          'Destroyer Fleet Strength value'),
            (    'Navy Strength',                  'Frigate Fleet Strength'),
            (    'Navy Strength',            'Frigate Fleet Strength value'),
            (         'Finances',                 'defense spending budget'),
            (         'Finances',           'defense spending budget value'),
            (         'Finances',                           'External Debt'),
            (         'Finances',                     'External Debt value'),
            (        'Logistics',                          'Airport Totals'),
            (        'Logistics',                    'Airport Totals value'),
            ('Natural resources',                          'Oil Production'),
            ('Natural resources',                    'Oil Production value'),
            ('Natural resources',                         'Oil Consumption'),
            ('Natural resources',                   'Oil Consumption value'),
            ('Natural resources',                     'Proven Oil Reserves'),
            ('Natural resources',               'Proven Oil Reserves value'),
            (         'Manpower',                      'Available Manpower'),
            (         'Manpower',                'Available Manpower value'),
            (         'Manpower',                        'Total Population'),
            (         'Manpower',                  'Total Population value'),
            (        'Geography',                  'Total Square Land Area'),
            (        'Geography',            'Total Square Land Area value'),
            (        'Geography',                'Total Coastline Coverage'),
            (        'Geography',          'Total Coastline Coverage value'),
            (        'Geography',                 'Total Waterway Coverage'),
            (        'Geography',           'Total Waterway Coverage value'),
            (        'Geography',                   'Total Border Coverage'),
            (        'Geography',             'Total Border Coverage value')],
           )

## Implement basic steps to see how is your data looks like

In [22]:
df.columns.values

array([('2020 ranking', 'Military Strength'),
       ('2020 ranking', 'Military Strength Power Index'),
       ('Airforce Strength', 'Aircraft Strength'),
       ('Airforce Strength', 'Aircraft Strength value'),
       ('Airforce Strength', 'Fighter/Interceptor Strength'),
       ('Airforce Strength', 'Fighter/Interceptor Strength value'),
       ('Airforce Strength', 'Attack Aircraft Strength'),
       ('Airforce Strength', 'Attack Aircraft Strength value'),
       ('Airforce Strength', 'Transport Aircraft Fleet Strength'),
       ('Airforce Strength', 'Transport Aircraft Fleet Strength value'),
       ('Airforce Strength', 'Trainer Aircraft Fleet'),
       ('Airforce Strength', 'Trainer Aircraft Fleet value'),
       ('Airforce Strength', 'Helicopter Fleet Strength'),
       ('Airforce Strength', 'Helicopter Fleet Strength value'),
       ('Airforce Strength', 'Attack Helicopter Fleet Strength'),
       ('Airforce Strength', 'Attack Helicopter Fleet Strength value'),
       ('Land Strength', 'Tank Strength'),
       ('Land Strength', 'Tank Strength value'),
       ('Land Strength', 'AFV/APC Strength'),
       ('Land Strength', 'AFV/APC Strength value'),
       ('Land Strength', 'Self-Propelled Artillery Strength'),
       ('Land Strength', 'Self-Propelled Artillery Strength value'),
       ('Land Strength', 'Towed Artillery Strength'),
       ('Land Strength', 'Towed Artillery Strength value'),
       ('Land Strength', 'Rocket Projector Strength'),
       ('Land Strength', 'Rocket Projector Strength value'),
       ('Navy Strength', 'Navy Fleet Strengths'),
       ('Navy Strength', 'Navy Fleet Strengths value'),
       ('Navy Strength', 'Aircraft Carrier Fleet Strength'),
       ('Navy Strength', 'Aircraft Carrier Fleet Strength value'),
       ('Navy Strength', 'Submarine Fleet Strength'),
       ('Navy Strength', 'Submarine Fleet Strength value'),
       ('Navy Strength', 'Destroyer Fleet Strength'),
       ('Navy Strength', 'Destroyer Fleet Strength value'),
       ('Navy Strength', 'Frigate Fleet Strength'),
       ('Navy Strength', 'Frigate Fleet Strength value'),
       ('Finances', 'defense spending budget'),
       ('Finances', 'defense spending budget value'),
       ('Finances', 'External Debt'), ('Finances', 'External Debt value'),
       ('Logistics', 'Airport Totals'),
       ('Logistics', 'Airport Totals value'),
       ('Natural resources', 'Oil Production'),
       ('Natural resources', 'Oil Production value'),
       ('Natural resources', 'Oil Consumption'),
       ('Natural resources', 'Oil Consumption value'),
       ('Natural resources', 'Proven Oil Reserves'),
       ('Natural resources', 'Proven Oil Reserves value'),
       ('Manpower', 'Available Manpower'),
       ('Manpower', 'Available Manpower value'),
       ('Manpower', 'Total Population'),
       ('Manpower', 'Total Population value'),
       ('Geography', 'Total Square Land Area'),
       ('Geography', 'Total Square Land Area value'),
       ('Geography', 'Total Coastline Coverage'),
       ('Geography', 'Total Coastline Coverage value'),
       ('Geography', 'Total Waterway Coverage'),
       ('Geography', 'Total Waterway Coverage value'),
       ('Geography', 'Total Border Coverage'),
       ('Geography', 'Total Border Coverage value')], dtype=object)

In [23]:
df.columns = ['_'.join(tuple(map(str, t))) for t in df.columns.values]

In [24]:
df.columns.values

array(['2020 ranking_Military Strength',
       '2020 ranking_Military Strength Power Index',
       'Airforce Strength_Aircraft Strength',
       'Airforce Strength_Aircraft Strength value',
       'Airforce Strength_Fighter/Interceptor Strength',
       'Airforce Strength_Fighter/Interceptor Strength value',
       'Airforce Strength_Attack Aircraft Strength',
       'Airforce Strength_Attack Aircraft Strength value',
       'Airforce Strength_Transport Aircraft Fleet Strength',
       'Airforce Strength_Transport Aircraft Fleet Strength value',
       'Airforce Strength_Trainer Aircraft Fleet',
       'Airforce Strength_Trainer Aircraft Fleet value',
       'Airforce Strength_Helicopter Fleet Strength',
       'Airforce Strength_Helicopter Fleet Strength value',
       'Airforce Strength_Attack Helicopter Fleet Strength',
       'Airforce Strength_Attack Helicopter Fleet Strength value',
       'Land Strength_Tank Strength', 'Land Strength_Tank Strength value',
       'Land Strength_AFV/APC Strength',
       'Land Strength_AFV/APC Strength value',
       'Land Strength_Self-Propelled Artillery Strength',
       'Land Strength_Self-Propelled Artillery Strength value',
       'Land Strength_Towed Artillery Strength',
       'Land Strength_Towed Artillery Strength value',
       'Land Strength_Rocket Projector Strength',
       'Land Strength_Rocket Projector Strength value',
       'Navy Strength_Navy Fleet Strengths',
       'Navy Strength_Navy Fleet Strengths value',
       'Navy Strength_Aircraft Carrier Fleet Strength',
       'Navy Strength_Aircraft Carrier Fleet Strength value',
       'Navy Strength_Submarine Fleet Strength',
       'Navy Strength_Submarine Fleet Strength value',
       'Navy Strength_Destroyer Fleet Strength',
       'Navy Strength_Destroyer Fleet Strength value',
       'Navy Strength_Frigate Fleet Strength',
       'Navy Strength_Frigate Fleet Strength value',
       'Finances_defense spending budget',
       'Finances_defense spending budget value', 'Finances_External Debt',
       'Finances_External Debt value', 'Logistics_Airport Totals',
       'Logistics_Airport Totals value',
       'Natural resources_Oil Production',
       'Natural resources_Oil Production value',
       'Natural resources_Oil Consumption',
       'Natural resources_Oil Consumption value',
       'Natural resources_Proven Oil Reserves',
       'Natural resources_Proven Oil Reserves value',
       'Manpower_Available Manpower', 'Manpower_Available Manpower value',
       'Manpower_Total Population', 'Manpower_Total Population value',
       'Geography_Total Square Land Area',
       'Geography_Total Square Land Area value',
       'Geography_Total Coastline Coverage',
       'Geography_Total Coastline Coverage value',
       'Geography_Total Waterway Coverage',
       'Geography_Total Waterway Coverage value',
       'Geography_Total Border Coverage',
       'Geography_Total Border Coverage value'], dtype=object)

## Convert multi index columns to one level

In [25]:
df.rename(columns={'2020 ranking_Military Strength': 'country'}, inplace=True)

In [26]:
df.set_index('country', inplace=True)

## Detect and drop duplicated columns

In [27]:
df.describe().T

                                                    count         mean          std      min        25%        50%          75%         max
2020 ranking_Military Strength Power Index          138.0     1.460716     1.324018   0.0606     0.5748     1.0341     2.021525     10.1681
Airforce Strength_Aircraft Strength value           138.0   388.471014  1231.981859   0.0000    33.0000   111.0000   290.250000  13264.0000
Airforce Strength_Fighter/Interceptor Strength ...  138.0    81.565217   230.324777   0.0000     0.0000    17.0000    60.500000   2085.0000
Airforce Strength_Attack Aircraft Strength value    138.0    25.760870    94.528222   0.0000     0.0000     0.0000    15.750000    742.0000
Airforce Strength_Transport Aircraft Fleet Stre...  138.0    30.231884    92.330436   0.0000     3.0000     9.0000    26.000000    945.0000
Airforce Strength_Trainer Aircraft Fleet value      138.0    82.833333   240.803721   0.0000     4.2500    26.0000    79.250000   2643.0000
Airforce Strength_Helicopter Fleet Strength value   138.0   154.065217   520.183631   0.0000    15.2500    44.0000   126.750000   5768.0000
Airforce Strength_Attack Helicopter Fleet Stren...  138.0    25.623188    97.326091   0.0000     0.0000     2.0000    17.750000    967.0000
Land Strength_Tank Strength value                   138.0   646.565217  1515.463683   0.0000    19.2500   153.0000   436.250000  12950.0000
Land Strength_AFV/APC Strength value                138.0  2485.695652  5410.546392   0.0000   250.2500   734.5000  2000.000000  39253.0000
Land Strength_Self-Propelled Artillery Strength...  138.0   212.159420   688.028987   0.0000     0.0000    23.0000    97.250000   6083.0000
Land Strength_Towed Artillery Strength value        138.0   393.978261   805.781703   0.0000    24.2500   108.0000   296.500000   4465.0000
Land Strength_Rocket Projector Strength value       138.0   156.934783   484.380984   0.0000     0.0000    24.0000    99.750000   3860.0000
Navy Strength_Navy Fleet Strengths value            124.0    84.983871   146.114165   0.0000    10.0000    38.0000    77.750000    984.0000
Navy Strength_Aircraft Carrier Fleet Strength v...  115.0     0.382609     1.971653   0.0000     0.0000     0.0000     0.000000     20.0000
Navy Strength_Submarine Fleet Strength value        115.0     4.800000    13.706958   0.0000     0.0000     0.0000     4.000000     83.0000
Navy Strength_Destroyer Fleet Strength value        115.0     2.052174    10.000740   0.0000     0.0000     0.0000     0.000000     91.0000
Navy Strength_Frigate Fleet Strength value          115.0     3.521739     6.481211   0.0000     0.0000     0.0000     5.500000     52.0000
Logistics_Airport Totals value                      138.0   290.043478  1212.967393   2.0000    33.5000    68.0000   150.750000  13513.0000
Geography_Total Border Coverage value               129.0  3964.224806  3760.099671  29.0000  1587.0000  2816.0000  5267.000000  22457.0000

In [28]:
df.describe(include=object).T

                                                    count unique             top  freq
Airforce Strength_Aircraft Strength                   138    138     Afghanistan     1
Airforce Strength_Fighter/Interceptor Strength        138    138     Afghanistan     1
Airforce Strength_Attack Aircraft Strength            138    138     Afghanistan     1
Airforce Strength_Transport Aircraft Fleet Stre...    138    138     Afghanistan     1
Airforce Strength_Trainer Aircraft Fleet              138    138     Afghanistan     1
Airforce Strength_Helicopter Fleet Strength           138    138     Afghanistan     1
Airforce Strength_Attack Helicopter Fleet Strength    138    138     Afghanistan     1
Land Strength_Tank Strength                           138    138     Afghanistan     1
Land Strength_AFV/APC Strength                        138    138     Afghanistan     1
Land Strength_Self-Propelled Artillery Strength       138    138     Afghanistan     1
Land Strength_Towed Artillery Strength                138    138     Afghanistan     1
Land Strength_Rocket Projector Strength               138    138     Afghanistan     1
Navy Strength_Navy Fleet Strengths                    124    124     Afghanistan     1
Navy Strength_Aircraft Carrier Fleet Strength         115    115     Afghanistan     1
Navy Strength_Submarine Fleet Strength                115    115     Afghanistan     1
Navy Strength_Destroyer Fleet Strength                115    115     Afghanistan     1
Navy Strength_Frigate Fleet Strength                  115    115     Afghanistan     1
Finances_defense spending budget                      138    138     Afghanistan     1
Finances_defense spending budget value                138    124  2,50,00,00,000     3
Finances_External Debt                                138    138     Afghanistan     1
Finances_External Debt value                          138    138  2,84,00,00,000     1
Logistics_Airport Totals                              138    138     Afghanistan     1
Natural resources_Oil Production                      138    138     Afghanistan     1
Natural resources_Oil Production value              138.0   88.0             0.0  46.0
Natural resources_Oil Consumption                     138    138     Afghanistan     1
Natural resources_Oil Consumption value             138.0  102.0         18500.0   4.0
Natural resources_Proven Oil Reserves                 138    138     Afghanistan     1
Natural resources_Proven Oil Reserves value         138.0   84.0             0.0  46.0
Manpower_Available Manpower                           138    138     Afghanistan     1
Manpower_Available Manpower value                     138    138     1,43,25,743     1
Manpower_Total Population                             138    138     Afghanistan     1
Manpower_Total Population value                       138    138     3,49,40,837     1
Geography_Total Square Land Area                      138    138     Afghanistan     1
Geography_Total Square Land Area value                138    138        6,52,230     1
Geography_Total Coastline Coverage                    109    109     Afghanistan     1
Geography_Total Coastline Coverage value            109.0  104.0           853.0   2.0
Geography_Total Waterway Coverage                     138    138     Afghanistan     1
Geography_Total Waterway Coverage value             138.0   92.0             0.0  38.0
Geography_Total Border Coverage                       129    129     Afghanistan     1

In [29]:
df.columns.str.findall(".*value")

Index([                                                           [],                                                            [],                 ['Airforce Strength_Aircraft Strength value'],                                                            [],      ['Airforce Strength_Fighter/Interceptor Strength value'],                                                            [],          ['Airforce Strength_Attack Aircraft Strength value'],                                                            [], ['Airforce Strength_Transport Aircraft Fleet Strength value'],                                                            [],            ['Airforce Strength_Trainer Aircraft Fleet value'],                                                            [],         ['Airforce Strength_Helicopter Fleet Strength value'],                                                            [],  ['Airforce Strength_Attack Helicopter Fleet Strength value'],
                                                                  [],                         ['Land Strength_Tank Strength value'],                                                            [],                      ['Land Strength_AFV/APC Strength value'],                                                            [],     ['Land Strength_Self-Propelled Artillery Strength value'],                                                            [],              ['Land Strength_Towed Artillery Strength value'],                                                            [],             ['Land Strength_Rocket Projector Strength value'],                                                            [],                  ['Navy Strength_Navy Fleet Strengths value'],                                                            [],       ['Navy Strength_Aircraft Carrier Fleet Strength value'],                                                            [],
                    ['Navy Strength_Submarine Fleet Strength value'],                                                            [],              ['Navy Strength_Destroyer Fleet Strength value'],                                                            [],                ['Navy Strength_Frigate Fleet Strength value'],                                                            [],                    ['Finances_defense spending budget value'],                                                            [],                              ['Finances_External Debt value'],                                                            [],                            ['Logistics_Airport Totals value'],                                                            [],                    ['Natural resources_Oil Production value'],                                                            [],                   ['Natural resources_Oil Consumption value'],
                                                                  [],               ['Natural resources_Proven Oil Reserves value'],                                                            [],                         ['Manpower_Available Manpower value'],                                                            [],                           ['Manpower_Total Population value'],                                                            [],                    ['Geography_Total Square Land Area value'],                                                            [],                  ['Geography_Total Coastline Coverage value'],                                                            [],                   ['Geography_Total Waterway Coverage value'],                                                            [],                     ['Geography_Total Border Coverage value']],
      dtype='object')

In [30]:
value_columns= [i[0] for i in df.columns.str.findall(".*value") if i !=[]]
value_columns

['Airforce Strength_Aircraft Strength value',
 'Airforce Strength_Fighter/Interceptor Strength value',
 'Airforce Strength_Attack Aircraft Strength value',
 'Airforce Strength_Transport Aircraft Fleet Strength value',
 'Airforce Strength_Trainer Aircraft Fleet value',
 'Airforce Strength_Helicopter Fleet Strength value',
 'Airforce Strength_Attack Helicopter Fleet Strength value',
 'Land Strength_Tank Strength value',
 'Land Strength_AFV/APC Strength value',
 'Land Strength_Self-Propelled Artillery Strength value',
 'Land Strength_Towed Artillery Strength value',
 'Land Strength_Rocket Projector Strength value',
 'Navy Strength_Navy Fleet Strengths value',
 'Navy Strength_Aircraft Carrier Fleet Strength value',
 'Navy Strength_Submarine Fleet Strength value',
 'Navy Strength_Destroyer Fleet Strength value',
 'Navy Strength_Frigate Fleet Strength value',
 'Finances_defense spending budget value',
 'Finances_External Debt value',
 'Logistics_Airport Totals value',
 'Natural resources_Oil Production value',
 'Natural resources_Oil Consumption value',
 'Natural resources_Proven Oil Reserves value',
 'Manpower_Available Manpower value',
 'Manpower_Total Population value',
 'Geography_Total Square Land Area value',
 'Geography_Total Coastline Coverage value',
 'Geography_Total Waterway Coverage value',
 'Geography_Total Border Coverage value']

In [33]:
df.drop([i for i in df.columns if i not in value_columns]  , axis = 1, inplace = True)

In [34]:
df

,Airforce Strength_Aircraft Strength value,Airforce Strength_Fighter/Interceptor Strength value,Airforce Strength_Attack Aircraft Strength value,Airforce Strength_Transport Aircraft Fleet Strength value,Airforce Strength_Trainer Aircraft Fleet value,Airforce Strength_Helicopter Fleet Strength value,Airforce Strength_Attack Helicopter Fleet Strength value,Land Strength_Tank Strength value,Land Strength_AFV/APC Strength value,Land Strength_Self-Propelled Artillery Strength value,Land Strength_Towed Artillery Strength value,Land Strength_Rocket Projector Strength value,Navy Strength_Navy Fleet Strengths value,Navy Strength_Aircraft Carrier Fleet Strength value,Navy Strength_Submarine Fleet Strength value,Navy Strength_Destroyer Fleet Strength value,Navy Strength_Frigate Fleet Strength value,Finances_defense spending budget value,Finances_External Debt value,Logistics_Airport Totals value,Natural resources_Oil Production value,Natural resources_Oil Consumption value,Natural resources_Proven Oil Reserves value,Manpower_Available Manpower value,Manpower_Total Population value,Geography_Total Square Land Area value,Geography_Total Coastline Coverage value,Geography_Total Waterway Coverage value,Geography_Total Border Coverage value
country,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Afghanistan,260.0,0.0,25.0,30.0,0.0,187.0,0.0,0.0,1062.0,0.0,176.0,50.0,0.0,0.0,0.0,0.0,0.0,"12,00,00,00,000","2,84,00,00,000",43.0,0.0,5500.0,0.0,"1,43,25,743","3,49,40,837","6,52,230",0.0,1200.0,5987.0
Albania,19.0,0.0,0.0,0.0,0.0,19.0,0.0,0.0,467.0,0.0,0.0,0.0,38.0,0.0,0.0,0.0,0.0,"25,00,00,000","9,50,50,00,000",4.0,16000.0,42500.0,"16,83,00,000","15,19,438","30,57,220",28748.0,362.0,41.0,691.0
Algeria,551.0,103.0,22.0,59.0,87.0,257.0,45.0,880.0,7361.0,320.0,240.0,316.0,201.0,0.0,6.0,0.0,5.0,"13,00,00,00,000","6,26,00,00,000",157.0,"13,06,000","3,25,000","12,20,00,00,000","2,07,41,263","4,16,57,488","23,81,741",998.0,0.0,6734.0
Angola,295.0,72.0,18.0,30.0,47.0,126.0,15.0,379.0,595.0,28.0,357.0,115.0,57.0,0.0,0.0,0.0,0.0,"7,00,00,00,000","42,08,00,00,000",176.0,"16,66,000",82300.0,"8,27,30,00,000","62,44,205","3,03,55,880","12,46,700",1600.0,1300.0,5369.0
Argentina,227.0,24.0,7.0,9.0,64.0,100.0,0.0,370.0,739.0,83.0,172.0,26.0,49.0,0.0,2.0,4.0,0.0,"4,20,00,00,000","2,14,90,00,00,000",1138.0,"4,79,400","6,85,000","2,18,50,00,000","2,01,79,430","4,46,94,198","27,80,400",4989.0,11000.0,11968.0
Armenia,64.0,0.0,9.0,3.0,13.0,37.0,20.0,110.0,748.0,38.0,150.0,68.0,0.0,NaN,NaN,NaN,NaN,"1,38,50,00,000","10,41,00,00,000",11.0,0.0,47500.0,0.0,"16,96,085","30,38,217",29743.0,NaN,0.0,1570.0
Australia,464.0,82.0,6.0,38.0,174.0,133.0,22.0,59.0,3051.0,0.0,54.0,0.0,48.0,2.0,6.0,2.0,8.0,"26,30,00,00,000","17,14,00,00,00,000",480.0,"2,63,000","10,05,000","1,82,10,00,000","1,08,08,002","2,34,70,145","77,41,220",25760.0,2000.0,NaN
Austria,120.0,15.0,0.0,11.0,32.0,62.0,0.0,56.0,467.0,33.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,"3,38,00,00,000","6,30,80,00,00,000",52.0,14260.0,"2,15,000","4,30,00,000","40,17,691","87,93,370",83871.0,NaN,0.0,2524.0
Azerbaijan,147.0,17.0,12.0,1.0,29.0,88.0,17.0,570.0,1451.0,187.0,227.0,162.0,31.0,0.0,4.0,0.0,1.0,"2,80,50,00,000","17,41,00,00,000",37.0,"7,89,300","1,80,000","7,00,00,00,000","50,42,346","1,00,46,516",86600.0,713.0,0.0,2468.0
Bahrain,109.0,17.0,0.0,2.0,37.0,65.0,22.0,180.0,843.0,33.0,26.0,17.0,39.0,0.0,0.0,0.0,1.0,"1,41,50,00,000","52,15,00,00,000",4.0,45000.0,55000.0,"12,46,00,000","8,06,505","14,22,659",760.0,161.0,0.0,NaN
Bangladesh,177.0,44.0,0.0,11.0,57.0,67.0,0.0,276.0,1230.0,18.0,419.0,72.0,112.0,0.0,2.0,0.0,8.0,"3,80,00,00,000","50,26,00,00,000",18.0,3666.0,"1,12,000","2,80,00,000","7,89,13,289","15,94,53,001","1,43,998",580.0,8370.0,4413.0
Belarus,202.0,39.0,68.0,4.0,28.0,63.0,21.0,532.0,1560.0,482.0,228.0,238.0,0.0,NaN,NaN,NaN,NaN,"62,37,02,800","39,92,00,00,000",65.0,32000.0,"1,90,000","19,80,00,000","49,82,905","95,27,543","2,07,600",NaN,2500.0,3599.0
Belgium,148.0,43.0,0.0,12.0,64.0,29.0,0.0,0.0,984.0,0.0,0.0,0.0,17.0,0.0,0.0,0.0,2.0,"4,92,10,00,000","12,81,00,00,00,000",41.0,0.0,"6,45,000",0.0,"48,33,107","1,15,70,762",30528.0,67.0,2043.0,1297.0
Bhutan,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,27.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,"2,51,20,000","2,67,10,00,000",2.0,0.0,2000.0,0.0,"1,76,808","7,66,397",38394.0,NaN,0.0,1136.0
Bolivia,69.0,0.0,0.0,14.0,23.0,38.0,0.0,54.0,137.0,0.0,86.0,0.0,173.0,0.0,0.0,0.0,0.0,"66,00,00,000","12,81,00,00,000",855.0,59330.0,60000.0,"21,15,00,000","50,75,416","1,13,06,341","10,98,581",NaN,10000.0,7252.0
Bosnia and Herzegovina,19.0,0.0,0.0,0.0,0.0,19.0,0.0,320.0,332.0,24.0,837.0,143.0,0.0,0.0,0.0,0.0,0.0,"16,50,00,000","10,87,00,00,000",24.0,0.0,32500.0,0.0,"23,94,632","38,49,891",51197.0,20.0,0.0,1543.0
Botswana,45.0,10.0,0.0,11.0,8.0,16.0,0.0,55.0,245.0,0.0,30.0,20.0,NaN,NaN,NaN,NaN,NaN,"45,00,00,000","2,18,70,00,000",74.0,0.0,16500.0,0.0,"9,62,617","22,49,104","5,81,730",NaN,0.0,4347.0
Brazil,715.0,43.0,78.0,126.0,198.0,242.0,12.0,437.0,1820.0,132.0,565.0,84.0,112.0,0.0,6.0,0.0,7.0,"27,80,00,00,000","5,47,40,00,00,000",4093.0,"26,22,000","30,20,000","13,00,00,00,000","10,77,64,996","20,88,46,892","85,14,877",7491.0,50000.0,16145.0
Bulgaria,63.0,13.0,4.0,5.0,20.0,25.0,2.0,710.0,2000.0,506.0,350.0,192.0,29.0,0.0,0.0,0.0,4.0,"1,07,90,00,000","42,06,00,00,000",68.0,1000.0,"1,15,000","1,50,00,000","32,78,916","70,57,504","1,10,880",354.0,470.0,1806.0
Burkina Faso,16.0,0.0,3.0,1.0,4.0,8.0,2.0,0.0,350.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,"13,00,00,000","3,05,60,00,000",23.0,0.0,10500.0,0.0,"78,00,000","1,97,42,715","2,74,200",NaN,0.0,3611.0
Cambodia,22.0,0.0,0.0,5.0,0.0,17.0,0.0,263.0,340.0,0.0,150.0,570.0,27.0,0.0,0.0,0.0,0.0,"60,40,00,000","11,87,00,00,000",16.0,0.0,42500.0,0.0,"81,20,963","1,64,49,519","1,81,035",443.0,3700.0,2530.0
Cameroon,29.0,0.0,0.0,6.0,6.0,15.0,0.0,0.0,222.0,8.0,61.0,20.0,64.0,0.0,0.0,0.0,0.0,"34,70,00,000","9,37,50,00,000",33.0,75720.0,32500.0,"20,00,00,000","94,87,157","2,56,40,965","4,75,440",400.0,0.0,5018.0
Canada,385.0,62.0,0.0,38.0,135.0,145.0,0.0,80.0,1973.0,0.0,133.0,0.0,64.0,0.0,4.0,0.0,12.0,"22,50,00,00,000","16,08,00,00,00,000",1467.0,"39,77,000","25,00,000","1,69,70,00,00,000","1,61,10,865","3,58,81,659","99,84,670","2,02,080",636.0,8893.0
Central African Republic,3.0,0.0,0.0,2.0,0.0,1.0,0.0,4.0,55.0,0.0,20.0,0.0,NaN,NaN,NaN,NaN,NaN,"2,00,00,000","77,99,00,000",39.0,0.0,4500.0,0.0,"23,48,581","57,45,062","6,22,984",NaN,2800.0,5920.0
Chad,35.0,0.0,6.0,6.0,4.0,17.0,3.0,60.0,372.0,10.0,51.0,10.0,NaN,NaN,NaN,NaN,NaN,"20,00,00,000","1,72,40,00,000",59.0,"1,28,000","1,00,000","1,50,00,00,000","60,30,834","1,58,33,116","12,84,000",NaN,0.0,6406.0
Chile,282.0,44.0,0.0,30.0,93.0,92.0,0.0,300.0,1430.0,48.0,158.0,10.0,69.0,0.0,4.0,0.0,10.0,"4,25,00,00,000","1,83,40,00,00,000",481.0,3244.0,"3,25,000","15,00,00,000","86,57,902","1,79,25,262","7,56,102",6435.0,12290.0,7801.0
China,3210.0,1232.0,371.0,224.0,314.0,911.0,281.0,3500.0,33000.0,3800.0,3600.0,2650.0,777.0,2.0,74.0,36.0,52.0,"2,37,00,00,00,000","15,98,00,00,00,000",507.0,"38,38,000","1,35,00,000","25,62,00,00,000","75,28,55,402","1,38,46,88,986","95,96,961",14500.0,"1,10,000",22457.0
Colombia,469.0,21.0,38.0,76.0,80.0,224.0,0.0,0.0,595.0,6.0,110.0,0.0,453.0,0.0,11.0,0.0,4.0,"10,60,00,00,000","1,24,60,00,00,000",836.0,"8,53,600","3,00,000","2,00,20,00,000","2,40,84,498","4,81,68,996","11,38,910",3208.0,24725.0,6672.0
Croatia,78.0,12.0,0.0,0.0,27.0,47.0,0.0,72.0,604.0,24.0,151.0,105.0,28.0,0.0,0.0,0.0,0.0,"80,00,00,000","48,10,00,00,000",69.0,14000.0,82000.0,"7,10,00,000","20,88,265","42,70,480",56594.0,5835.0,785.0,2237.0
Cuba,80.0,38.0,0.0,2.0,26.0,14.0,4.0,1180.0,670.0,100.0,150.0,100.0,12.0,0.0,0.0,0.0,2.0,"50,00,00,000","30,06,00,00,000",133.0,50000.0,"1,52,000","12,40,00,000","59,80,621","1,11,16,396","1,10,860",3735.0,240.0,29.0
Czechia,95.0,12.0,16.0,8.0,15.0,44.0,15.0,116.0,682.0,86.0,85.0,0.0,NaN,NaN,NaN,NaN,NaN,"2,96,90,00,000","2,05,20,00,00,000",128.0,2000.0,"2,00,000","1,50,00,000","50,11,174","1,06,86,269",78867.0,NaN,664.0,2046.0
Democratic Republic of the Congo,53.0,2.0,4.0,13.0,0.0,34.0,8.0,175.0,100.0,16.0,120.0,57.0,20.0,0.0,0.0,0.0,0.0,"10,00,00,000","4,96,30,00,000",198.0,19160.0,10500.0,"18,00,00,000","3,41,12,410","8,52,81,024","23,44,858",37.0,15000.0,10481.0
Denmark,113.0,33.0,0.0,4.0,38.0,35.0,0.0,57.0,972.0,22.0,0.0,0.0,74.0,0.0,0.0,0.0,9.0,"4,76,00,00,000","4,84,80,00,00,000",80.0,"1,37,100","1,62,000","49,06,00,000","25,90,457","58,09,502",43094.0,7314.0,400.0,140.0
Dominican Republic,49.0,0.0,8.0,10.0,4.0,28.0,0.0,6.0,20.0,0.0,20.0,0.0,33.0,0.0,0.0,0.0,0.0,"76,00,00,000","29,16,00,00,000",36.0,0.0,"1,25,000",0.0,"48,19,818","1,02,98,756",48320.0,1288.0,350.0,376.0
Ecuador,108.0,9.0,0.0,22.0,29.0,50.0,0.0,232.0,413.0,15.0,102.0,26.0,19.0,0.0,2.0,0.0,2.0,"2,50,00,00,000","39,29,00,00,000",432.0,"5,31,300","2,82,000","8,27,30,00,000","76,96,551","1,64,98,502","2,83,560",2237.0,1500.0,2237.0
Egypt,1054.0,215.0,88.0,59.0,387.0,294.0,81.0,4295.0,11700.0,1139.0,2189.0,1084.0,316.0,2.0,8.0,0.0,7.0,"11,20,00,00,000","77,47,00,00,000",83.0,"5,89,400","8,32,000","4,40,00,00,000","4,29,46,553","9,94,13,317","10,01,450",2450.0,3500.0,2612.0
El Salvador,51.0,0.0,15.0,2.0,3.0,31.0,0.0,0.0,125.0,0.0,70.0,0.0,4.0,0.0,0.0,0.0,0.0,"16,70,00,000","15,51,00,00,000",68.0,0.0,45600.0,0.0,"31,06,010","61,87,271",21041.0,307.0,0.0,590.0
Estonia,7.0,0.0,0.0,2.0,5.0,4.0,0.0,0.0,181.0,18.0,66.0,0.0,6.0,0.0,0.0,0.0,0.0,"68,50,00,000","19,05,00,00,000",18.0,0.0,27500.0,0.0,"5,96,014","12,44,288",45228.0,3794.0,335.0,657.0
Ethiopia,86.0,24.0,0.0,9.0,20.0,33.0,8.0,400.0,114.0,67.0,650.0,183.0,NaN,NaN,NaN,NaN,NaN,"35,00,00,000","26,05,00,00,000",57.0,0.0,55000.0,"4,28,000","4,11,43,474","10,83,86,391","11,04,300",NaN,"1,04,300",5925.0
Finland,194.0,55.0,0.0,11.0,105.0,127.0,0.0,200.0,2050.0,100.0,627.0,75.0,246.0,0.0,0.0,0.0,0.0,"3,57,00,00,000","1,50,60,00,00,000",148.0,0.0,"2,05,000",0.0,"23,07,420","55,37,364","3,38,145",1250.0,7842.0,2563.0
France,1229.0,269.0,0.0,121.0,187.0,589.0,62.0,528.0,6028.0,109.0,12.0,13.0,180.0,4.0,9.0,11.0,11.0,"41,50,00,00,000","53,60,00,00,00,000",464.0,15170.0,"16,00,000","7,23,50,000","3,01,11,868","6,73,64,357","6,43,801",4853.0,8501.0,4072.0
Gabon,23.0,6.0,0.0,2.0,0.0,15.0,0.0,0.0,70.0,0.0,16.0,0.0,10.0,0.0,0.0,0.0,0.0,"8,30,00,000","6,49,00,00,000",44.0,"1,98,800",16500.0,"2,00,00,00,000","8,42,741","21,19,036","2,67,667",885.0,1600.0,3261.0
Georgia,66.0,0.0,10.0,2.0,12.0,38.0,9.0,143.0,950.0,69.0,133.0,51.0,9.0,0.0,0.0,0.0,0.0,"32,70,00,000","16,99,00,00,000",22.0,400.0,18500.0,"3,50,00,000","22,49,744","49,26,087",69700.0,310.0,4349.0,1814.0
Germany,712.0,128.0,74.0,71.0,26.0,386.0,56.0,245.0,4583.0,108.0,0.0,38.0,80.0,0.0,6.0,0.0,9.0,"50,00,00,00,000","53,26,00,00,00,000",539.0,43410.0,"25,00,000","14,54,00,000","3,70,10,559","8,04,57,737","3,57,022",2389.0,7467.0,3694.0
Ghana,24.0,0.0,0.0,3.0,6.0,13.0,0.0,0.0,150.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,"71,00,00,000","22,14,00,00,000",10.0,"1,51,000",65000.0,"66,00,00,000","1,25,61,805","2,81,02,471","2,38,533",539.0,1293.0,2420.0
Greece,566.0,187.0,0.0,15.0,143.0,231.0,29.0,1355.0,3691.0,547.0,463.0,152.0,116.0,0.0,11.0,0.0,13.0,"4,84,40,00,000","5,06,60,00,00,000",77.0,2753.0,"3,50,000","1,00,00,000","49,93,347","1,07,61,523","1,31,957",13676.0,6.0,1110.0
Guatemala,33.0,0.0,4.0,8.0,6.0,15.0,0.0,12.0,135.0,0.0,106.0,0.0,26.0,0.0,0.0,0.0,0.0,"24,00,00,000","22,92,00,00,000",291.0,9666.0,85000.0,"8,30,70,000","70,63,622","1,65,81,273","1,08,889",400.0,990.0,1667.0
Honduras,46.0,3.0,9.0,11.0,10.0,12.0,0.0,19.0,92.0,0.0,176.0,0.0,59.0,0.0,0.0,0.0,0.0,"20,50,00,000","8,62,50,00,000",103.0,0.0,60000.0,0.0,"41,04,696","91,82,766","1,12,090",832.0,465.0,1575.0
Hungary,47.0,12.0,0.0,5.0,6.0,24.0,8.0,30.0,944.0,0.0,300.0,0.0,NaN,NaN,NaN,NaN,NaN,"2,08,00,00,000","1,38,10,00,00,000",41.0,14000.0,"1,45,000","2,51,00,000","46,18,081","98,25,704","1,03,000",NaN,1622.0,2106.0
India,2123.0,538.0,172.0,250.0,359.0,722.0,23.0,4292.0,8686.0,235.0,4060.0,266.0,285.0,1.0,16.0,10.0,13.0,"61,00,00,00,000","5,01,60,00,00,000",346.0,"7,33,900","50,00,000","4,62,10,00,000","62,24,80,340","1,29,68,34,042","32,87,263",7000.0,14500.0,13888.0
Indonesia,462.0,41.0,39.0,54.0,109.0,177.0,16.0,313.0,1178.0,153.0,366.0,36.0,282.0,0.0,5.0,0.0,7.0,"7,60,00,00,000","3,44,40,00,00,000",673.0,"8,01,700","16,30,000","3,23,00,00,000","13,08,68,127","26,27,87,403","19,04,569",54716.0,21579.0,2958.0
Iran,509.0,155.0,23.0,62.0,94.0,100.0,12.0,2056.0,4300.0,570.0,2088.0,1935.0,398.0,0.0,34.0,0.0,7.0,"19,60,00,00,000","7,99,50,00,000",319.0,"44,69,000","20,00,000","1,58,40,00,00,000","4,73,24,105","8,30,24,745","16,48,195",2440.0,850.0,5894.0
Iraq,348.0,26.0,33.0,16.0,102.0,186.0,40.0,309.0,4739.0,44.0,120.0,30.0,60.0,0.0,0.0,0.0,0.0,"1,73,00,00,000","73,02,00,00,000",102.0,"44,54,000","8,25,000","1,42,50,00,00,000","1,63,99,240","4,01,94,216","4,38,317",58.0,5279.0,3809.0
Ireland,19.0,0.0,0.0,0.0,8.0,8.0,0.0,0.0,124.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,"87,00,00,000","24,70,00,00,00,000",40.0,0.0,"1,45,000",0.0,"23,66,779","50,68,050",70273.0,1448.0,956.0,443.0
Israel,589.0,259.0,18.0,15.0,154.0,146.0,48.0,2760.0,10275.0,650.0,300.0,100.0,65.0,0.0,5.0,0.0,0.0,"20,00,00,00,000","88,66,00,00,000",47.0,390.0,"2,50,000","1,27,30,000","36,47,983","84,24,904",20770.0,273.0,0.0,1068.0
Italy,860.0,99.0,110.0,38.0,185.0,439.0,59.0,200.0,6947.0,54.0,108.0,21.0,249.0,2.0,8.0,4.0,12.0,"27,80,00,00,000","24,44,00,00,00,000",129.0,77530.0,"13,00,000","55,67,00,000","2,80,11,003","6,22,46,674","3,01,340",7600.0,2400.0,1836.0
Ivory Coast,8.0,0.0,0.0,4.0,0.0,4.0,3.0,15.0,109.0,0.0,7.0,6.0,10.0,0.0,0.0,0.0,0.0,"55,00,00,000","13,07,00,00,000",27.0,54000.0,25600.0,"10,00,00,000","1,11,60,747","2,62,60,582","3,22,463",515.0,980.0,3458.0
Japan,1561.0,279.0,12.0,60.0,427.0,637.0,119.0,1004.0,3130.0,238.0,500.0,99.0,155.0,4.0,20.0,40.0,0.0,"49,00,00,00,000","32,40,00,00,00,000",175.0,3841.0,"40,00,000","4,41,20,000","5,38,73,803","12,61,68,156","3,77,915",29751.0,1770.0,NaN
Jordan,278.0,44.0,4.0,16.0,75.0,146.0,47.0,1313.0,2897.0,461.0,72.0,88.0,37.0,0.0,0.0,0.0,0.0,"2,60,00,00,000","29,34,00,00,000",18.0,22.0,"1,10,000","10,00,000","33,46,692","1,04,58,413",89342.0,26.0,540.0,1744.0
Kazakhstan,222.0,76.0,39.0,18.0,18.0,71.0,18.0,650.0,800.0,0.0,300.0,100.0,15.0,0.0,0.0,0.0,0.0,"4,00,00,00,000","1,67,50,00,00,000",96.0,"17,77,000","2,45,000","30,00,00,00,000","85,85,003","1,87,44,548","27,24,900",26.0,0.0,13364.0
Kenya,150.0,17.0,0.0,20.0,32.0,79.0,0.0,76.0,479.0,30.0,25.0,0.0,19.0,0.0,0.0,0.0,0.0,"12,10,00,000","27,59,00,00,000",197.0,0.0,82000.0,0.0,"1,96,00,998","4,83,97,527","5,80,367",536.0,0.0,3457.0
Kuwait,85.0,27.0,0.0,2.0,13.0,40.0,16.0,367.0,745.0,98.0,0.0,27.0,38.0,0.0,0.0,0.0,0.0,"6,83,10,00,000","47,24,00,00,000",7.0,"27,53,000","3,45,000","1,01,50,00,00,000","16,41,971","29,16,467",17818.0,499.0,0.0,475.0
Kyrgyzstan,5.0,0.0,0.0,0.0,0.0,5.0,2.0,150.0,385.0,30.0,141.0,21.0,NaN,NaN,NaN,NaN,NaN,"2,00,00,000","8,16,40,00,000",28.0,1000.0,17200.0,"4,00,00,000","30,29,935","58,49,296","1,99,951",NaN,600.0,4573.0
Laos,33.0,0.0,0.0,2.0,4.0,27.0,0.0,65.0,30.0,0.0,62.0,0.0,36.0,0.0,0.0,0.0,0.0,"1,85,00,000","14,90,00,00,000",41.0,0.0,4500.0,0.0,"32,48,143","72,34,171","2,36,800",NaN,4600.0,5274.0
Latvia,5.0,0.0,0.0,0.0,12.0,5.0,0.0,0.0,303.0,47.0,20.0,0.0,18.0,0.0,0.0,0.0,0.0,"72,40,00,000","40,02,00,00,000",42.0,0.0,32500.0,0.0,"8,40,595","19,23,559",64589.0,498.0,300.0,1370.0
Lebanon,70.0,0.0,9.0,0.0,0.0,55.0,0.0,366.0,2228.0,12.0,374.0,30.0,57.0,0.0,0.0,0.0,0.0,"2,50,00,00,000","39,30,00,00,000",8.0,0.0,"1,10,000",0.0,"21,35,026","61,00,075",10400.0,225.0,170.0,484.0
Liberia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"1,30,00,000","1,03,60,00,000",29.0,0.0,4500.0,0.0,"22,26,923","48,09,768","1,11,369",579.0,0.0,1667.0
Libya,114.0,17.0,2.0,4.0,62.0,26.0,7.0,250.0,450.0,50.0,100.0,55.0,5.0,0.0,0.0,0.0,1.0,"3,00,00,00,000","3,02,00,00,000",146.0,"8,97,100","3,15,000","48,36,00,00,000","35,52,871","67,54,507","17,59,540",1770.0,0.0,4339.0
Lithuania,10.0,0.0,0.0,5.0,0.0,5.0,0.0,0.0,420.0,56.0,54.0,0.0,12.0,0.0,0.0,0.0,0.0,"1,10,70,00,000","34,48,00,00,000",61.0,2000.0,72400.0,"1,20,00,000","17,79,322","27,93,284",65300.0,90.0,441.0,1545.0
Madagascar,6.0,0.0,0.0,0.0,0.0,6.0,0.0,12.0,103.0,0.0,25.0,0.0,8.0,0.0,0.0,0.0,0.0,"11,50,00,000","4,08,90,00,000",83.0,0.0,18500.0,0.0,"1,01,45,026","2,56,83,610","5,87,040",4828.0,600.0,NaN
Malaysia,170.0,26.0,13.0,18.0,40.0,65.0,0.0,74.0,1387.0,0.0,211.0,54.0,61.0,0.0,2.0,0.0,6.0,"4,00,00,00,000","2,17,20,00,00,000",114.0,"6,47,900","8,35,000","3,60,00,00,000","1,52,01,837","3,18,09,660","3,29,847",4675.0,7200.0,2742.0
Mali,29.0,9.0,0.0,6.0,5.0,8.0,6.0,80.0,248.0,0.0,50.0,32.0,NaN,NaN,NaN,NaN,NaN,"7,00,00,000","4,19,20,00,000",25.0,0.0,5500.0,0.0,"59,91,557","1,84,29,893","12,40,192",NaN,0.0,7908.0
Mauritania,28.0,0.0,2.0,6.0,9.0,4.0,0.0,35.0,95.0,0.0,224.0,0.0,5.0,0.0,0.0,0.0,0.0,"5,02,50,000","4,15,00,00,000",30.0,4000.0,18500.0,"2,00,00,000","15,55,374","38,40,429","10,30,700",754.0,0.0,5002.0
Mexico,484.0,3.0,33.0,43.0,206.0,202.0,0.0,0.0,2199.0,0.0,265.0,0.0,189.0,0.0,0.0,0.0,4.0,"7,00,00,00,000","4,45,80,00,00,000",1714.0,"19,81,000","20,00,000","7,64,00,00,000","6,04,60,418","12,59,59,205","19,64,375",9330.0,2900.0,4389.0
Moldova,3.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,341.0,9.0,52.0,11.0,NaN,NaN,NaN,NaN,NaN,"3,00,00,000","6,54,90,00,000",7.0,0.0,16320.0,0.0,"20,14,503","34,37,720",33851.0,NaN,558.0,1885.0
Mongolia,9.0,0.0,0.0,3.0,0.0,6.0,0.0,470.0,750.0,0.0,300.0,130.0,NaN,NaN,NaN,NaN,NaN,"15,50,00,000","25,33,00,00,000",44.0,20000.0,25000.0,0.0,"18,18,609","31,03,428","15,64,116",NaN,580.0,8082.0
Montenegro,9.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,26.0,0.0,12.0,18.0,18.0,0.0,0.0,0.0,2.0,"6,50,00,000","2,51,60,00,000",5.0,0.0,4860.0,0.0,"1,46,191","6,14,249",13812.0,294.0,0.0,680.0
Morocco,214.0,46.0,0.0,31.0,67.0,64.0,0.0,1443.0,2901.0,505.0,200.0,144.0,121.0,0.0,0.0,0.0,3.0,"10,00,00,00,000","51,48,00,00,000",55.0,160.0,"2,06,000","6,84,000","1,71,57,065","3,43,14,130","4,46,550",1835.0,0.0,2363.0
Mozambique,16.0,8.0,0.0,1.0,1.0,6.0,2.0,100.0,335.0,0.0,260.0,12.0,8.0,0.0,0.0,0.0,0.0,"24,50,00,000","10,91,00,00,000",98.0,0.0,22500.0,0.0,"46,29,744","2,72,33,789","7,99,380",2470.0,460.0,4783.0
Myanmar,276.0,59.0,21.0,27.0,82.0,86.0,9.0,434.0,1300.0,108.0,1612.0,84.0,187.0,0.0,1.0,0.0,5.0,"2,65,00,00,000","6,59,40,00,000",64.0,12000.0,42600.0,"13,90,00,000","3,02,58,643","5,56,22,506","6,76,578",1930.0,12800.0,6522.0
Namibia,30.0,6.0,0.0,3.0,14.0,7.0,2.0,7.0,410.0,0.0,50.0,4.0,8.0,0.0,0.0,0.0,0.0,"50,50,00,000","7,96,90,00,000",112.0,0.0,25000.0,0.0,"5,82,642","25,33,224","8,24,292",1572.0,0.0,4220.0
Nepal,16.0,0.0,0.0,3.0,0.0,13.0,0.0,0.0,214.0,0.0,84.0,0.0,NaN,NaN,NaN,NaN,NaN,"21,30,00,000","5,84,90,00,000",47.0,0.0,20000.0,0.0,"1,47,39,923","2,97,17,587","1,47,181",NaN,0.0,3159.0
Netherlands,168.0,61.0,1.0,4.0,27.0,75.0,28.0,18.0,1546.0,57.0,160.0,0.0,63.0,0.0,4.0,0.0,6.0,"12,41,90,00,000","40,63,00,00,00,000",29.0,18170.0,"8,40,000","11,32,00,000","78,20,960","1,71,51,228",41543.0,451.0,6237.0,1053.0
New Zealand,48.0,0.0,0.0,7.0,13.0,22.0,0.0,0.0,200.0,0.0,24.0,0.0,11.0,0.0,0.0,0.0,2.0,"4,30,00,00,000","91,62,00,00,000",123.0,31480.0,"1,50,000","5,69,00,000","21,15,989","45,45,627","2,67,710",15134.0,0.0,NaN
Nicaragua,19.0,0.0,0.0,5.0,1.0,14.0,0.0,104.0,265.0,0.0,654.0,163.0,30.0,0.0,0.0,0.0,0.0,"14,00,00,000","11,31,00,00,000",147.0,0.0,35000.0,0.0,"30,30,436","60,85,213","1,30,370",910.0,2220.0,1253.0
Niger,16.0,0.0,2.0,5.0,0.0,7.0,1.0,0.0,182.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,"32,50,00,000","3,72,80,00,000",30.0,11000.0,6500.0,"15,00,00,000","67,54,519","1,98,66,231","12,67,000",NaN,300.0,5834.0
Nigeria,129.0,8.0,13.0,21.0,47.0,44.0,15.0,253.0,1789.0,25.0,339.0,36.0,75.0,0.0,0.0,0.0,0.0,"2,15,50,00,000","40,96,00,00,000",54.0,"19,46,000","2,75,000","37,06,00,00,000","7,71,08,499","20,34,52,505","9,23,768",853.0,8600.0,4477.0

In [37]:
df.shape

(138, 29)

## Check for missing values

In [38]:
df.isnull().sum().sort_values(ascending=False)

Geography_Total Coastline Coverage value                     29
Navy Strength_Submarine Fleet Strength value                 23
Navy Strength_Frigate Fleet Strength value                   23
Navy Strength_Destroyer Fleet Strength value                 23
Navy Strength_Aircraft Carrier Fleet Strength value          23
Navy Strength_Navy Fleet Strengths value                     14
Geography_Total Border Coverage value                         9
Land Strength_Tank Strength value                             0
Land Strength_AFV/APC Strength value                          0
Geography_Total Waterway Coverage value                       0
Airforce Strength_Attack Aircraft Strength value              0
Geography_Total Square Land Area value                        0
Manpower_Total Population value                               0
Manpower_Available Manpower value                             0
Natural resources_Proven Oil Reserves value                   0
Natural resources_Oil Consumption value                       0
Natural resources_Oil Production value                        0
Logistics_Airport Totals value                                0
Finances_External Debt value                                  0
Finances_defense spending budget value                        0
Airforce Strength_Transport Aircraft Fleet Strength value     0
Airforce Strength_Trainer Aircraft Fleet value                0
Airforce Strength_Fighter/Interceptor Strength value          0
Airforce Strength_Helicopter Fleet Strength value             0
Airforce Strength_Attack Helicopter Fleet Strength value      0
Land Strength_Rocket Projector Strength value                 0
Land Strength_Towed Artillery Strength value                  0
Land Strength_Self-Propelled Artillery Strength value         0
Airforce Strength_Aircraft Strength value                     0
dtype: int64

In [40]:
df['Geography_Total Coastline Coverage value']

country
Afghanistan                              0.0
Albania                                362.0
Algeria                                998.0
Angola                                1600.0
Argentina                             4989.0
Armenia                                  NaN
Australia                            25760.0
Austria                                  NaN
Azerbaijan                             713.0
Bahrain                                161.0
Bangladesh                             580.0
Belarus                                  NaN
Belgium                                 67.0
Bhutan                                   NaN
Bolivia                                  NaN
Bosnia and Herzegovina                  20.0
Botswana                                 NaN
Brazil                                7491.0
Bulgaria                               354.0
Burkina Faso                             NaN
Cambodia                               443.0
Cameroon                               400.0
Canada                              2,02,080
Central African Republic                 NaN
Chad                                     NaN
Chile                                 6435.0
China                                14500.0
Colombia                              3208.0
Croatia                               5835.0
Cuba                                  3735.0
Czechia                                  NaN
Democratic Republic of the Congo        37.0
Denmark                               7314.0
Dominican Republic                    1288.0
Ecuador                               2237.0
Egypt                                 2450.0
El Salvador                            307.0
Estonia                               3794.0
Ethiopia                                 NaN
Finland                               1250.0
France                                4853.0
Gabon                                  885.0
Georgia                                310.0
Germany                               2389.0
Ghana                                  539.0
Greece                               13676.0
Guatemala                              400.0
Honduras                               832.0
Hungary                                  NaN
India                                 7000.0
Indonesia                            54716.0
Iran                                  2440.0
Iraq                                    58.0
Ireland                               1448.0
Israel                                 273.0
Italy                                 7600.0
Ivory Coast                            515.0
Japan                                29751.0
Jordan                                  26.0
Kazakhstan                              26.0
Kenya                                  536.0
Kuwait                                 499.0
Kyrgyzstan                               NaN
Laos                                     NaN
Latvia                                 498.0
Lebanon                                225.0
Liberia                                579.0
Libya                                 1770.0
Lithuania                               90.0
Madagascar                            4828.0
Malaysia                              4675.0
Mali                                     NaN
Mauritania                             754.0
Mexico                                9330.0
Moldova                                  NaN
Mongolia                                 NaN
Montenegro                             294.0
Morocco                               1835.0
Mozambique                            2470.0
Myanmar                               1930.0
Namibia                               1572.0
Nepal                                    NaN
Netherlands                            451.0
New Zealand                          15134.0
Nicaragua                              910.0
Niger                                    NaN
Nigeria                                853.0
North Korea                           2495.0
North Macedonia                          NaN
Norway                               25148.0
Oman                                  2092.0
Pakistan                              1046.0
Panama                                2490.0
Paraguay                                 NaN
Peru                                  2414.0
Philippines                          36289.0
Poland                                 440.0
Portugal                              1793.0
Qatar                                  563.0
Republic of the Congo                  169.0
Romania                                225.0
Russia                               37653.0
Saudi Arabia                          2640.0
Serbia                                   NaN
Sierra Leone                           402.0
Singapore                              193.0
Slovakia                                 NaN
Slovenia                                47.0
Somalia                               3025.0
South Africa                          2798.0
South Korea                           2413.0
South Sudan                              NaN
Spain                                 4964.0
Sri Lanka                             1340.0
Sudan                                  853.0
Suriname                               386.0
Sweden                                3218.0
Switzerland                              NaN
Syria                                  193.0
Taiwan                                1566.0
Tajikistan                               NaN
Tanzania                              1424.0
Thailand                              3219.0
Tunisia                               1148.0
Turkey                                7200.0
Turkmenistan                          1768.0
Uganda                                   NaN
Ukraine                               2782.0
United Arab Emirates                  1318.0
United Kingdom                       12429.0
United States                        19924.0
Uruguay                                660.0
Uzbekistan                             420.0
Venezuela                             2800.0
Vietnam                               3444.0
Yemen                                 1906.0
Zambia                                   NaN
Zimbabwe                                 NaN
Name: Geography_Total Coastline Coverage value, dtype: object

In [41]:
df['Navy Strength_Submarine Fleet Strength value']

country
Afghanistan                          0.0
Albania                              0.0
Algeria                              6.0
Angola                               0.0
Argentina                            2.0
Armenia                              NaN
Australia                            6.0
Austria                              NaN
Azerbaijan                           4.0
Bahrain                              0.0
Bangladesh                           2.0
Belarus                              NaN
Belgium                              0.0
Bhutan                               NaN
Bolivia                              0.0
Bosnia and Herzegovina               0.0
Botswana                             NaN
Brazil                               6.0
Bulgaria                             0.0
Burkina Faso                         NaN
Cambodia                             0.0
Cameroon                             0.0
Canada                               4.0
Central African Republic             NaN
Chad                                 NaN
Chile                                4.0
China                               74.0
Colombia                            11.0
Croatia                              0.0
Cuba                                 0.0
Czechia                              NaN
Democratic Republic of the Congo     0.0
Denmark                              0.0
Dominican Republic                   0.0
Ecuador                              2.0
Egypt                                8.0
El Salvador                          0.0
Estonia                              0.0
Ethiopia                             NaN
Finland                              0.0
France                               9.0
Gabon                                0.0
Georgia                              0.0
Germany                              6.0
Ghana                                0.0
Greece                              11.0
Guatemala                            0.0
Honduras                             0.0
Hungary                              NaN
India                               16.0
Indonesia                            5.0
Iran                                34.0
Iraq                                 0.0
Ireland                              0.0
Israel                               5.0
Italy                                8.0
Ivory Coast                          0.0
Japan                               20.0
Jordan                               0.0
Kazakhstan                           0.0
Kenya                                0.0
Kuwait                               0.0
Kyrgyzstan                           NaN
Laos                                 0.0
Latvia                               0.0
Lebanon                              0.0
Liberia                              0.0
Libya                                0.0
Lithuania                            0.0
Madagascar                           0.0
Malaysia                             2.0
Mali                                 NaN
Mauritania                           0.0
Mexico                               0.0
Moldova                              NaN
Mongolia                             NaN
Montenegro                           0.0
Morocco                              0.0
Mozambique                           0.0
Myanmar                              1.0
Namibia                              0.0
Nepal                                NaN
Netherlands                          4.0
New Zealand                          0.0
Nicaragua                            0.0
Niger                                NaN
Nigeria                              0.0
North Korea                         83.0
North Macedonia                      NaN
Norway                               6.0
Oman                                 0.0
Pakistan                             8.0
Panama                               0.0
Paraguay                             0.0
Peru                                 5.0
Philippines                          0.0
Poland                               3.0
Portugal                             2.0
Qatar                                0.0
Republic of the Congo                0.0
Romania                              0.0
Russia                              62.0
Saudi Arabia                         0.0
Serbia                               0.0
Sierra Leone                         0.0
Singapore                            0.0
Slovakia                             NaN
Slovenia                             0.0
Somalia                              0.0
South Africa                         3.0
South Korea                          NaN
South Sudan                         22.0
Spain                                3.0
Sri Lanka                            0.0
Sudan                                0.0
Suriname                             0.0
Sweden                               5.0
Switzerland                          NaN
Syria                                0.0
Taiwan                               4.0
Tajikistan                           NaN
Tanzania                             0.0
Thailand                             0.0
Tunisia                              0.0
Turkey                              12.0
Turkmenistan                         0.0
Uganda                               0.0
Ukraine                              0.0
United Arab Emirates                 0.0
United Kingdom                      10.0
United States                       66.0
Uruguay                              0.0
Uzbekistan                           NaN
Venezuela                            2.0
Vietnam                              6.0
Yemen                                0.0
Zambia                               0.0
Zimbabwe                             0.0
Name: Navy Strength_Submarine Fleet Strength value, dtype: float64

## Deal with missing values 
* Hint-1, use wikipedia to fill in missing values ​​comparing with similar countries
* Hint-2, Georeferences of countries can help you

In [ ]:
# submarine_fleet_strength_value : South Korea --> 22
# frigate_fleet_strength_value : South Korea --> 4
# destroyer_fleet_strength_value : South Korea --> 12

## Fix the dtypes

## Drop the features that not affect military power
* Hint-1,  Georeferences not proper features

## Visualy inspect the some features

## Decriptive statistics

# Data Preprocessing

# Modelling

## Hopkins Test 
#### Assess the clusterability of a dataset. A score between 0 and 1, a score around 0.5 express no clusterability, a score tending to 1 express an uniform distrubution so clustering can't be useful and  0 express  not an uniform distrubution hence clusterering can be useful.

## Clustering with K-means

### Elbow Method 
### We use this method to find optimal k value by looking up to break point of graph.

### Model Building and label visualisation

### Evaluate

## Hierarchical Clustering

### Dendogram

### Model Building and label visualisation

### Evaluate